export { useInfiniteQuery } from './composables/useInfiniteQuery.js';
export type { UseInfiniteQueryOptions, UseInfiniteQueryReturnType, } from './composables/useInfiniteQuery.js';
export { useIsFetching } from './composables/useIsFetching.js';
export type { QueryFilters } from './composables/useIsFetching.js';
export { useMutation } from './composables/useMutation.js';
export type { UseMutationOptions, UseMutationReturnType } from './composables/useMutation.js';
export { useIsMutating, useMutationState } from './composables/useMutationState.js';
export type { MutationFilters, MutationStateOptions } from './composables/useMutationState.js';
export { useQueries } from './composables/useQueries.js';
export type { UseQueriesOptions, UseQueriesResults } from './composables/useQueries.js';
export { useQuery } from './composables/useQuery.js';
export type { DefinedInitialQueryOptions, UndefinedInitialQueryOptions, UseQueryDefinedReturnType, UseQueryOptions, UseQueryReturnType, } from './composables/useQuery.js';
export { useQueryClient } from './composables/useQueryClient.js';
export { infiniteQueryOptions } from './infiniteQueryOptions.js';
export type { DefinedInitialDataInfiniteOptions, UndefinedInitialDataInfiniteOptions, } from './infiniteQueryOptions.js';
export { MutationCache } from './mutationCache.js';
export { QueryCache } from './queryCache.js';
export { QueryClient } from './queryClient.js';
export { queryOptions } from './queryOptions.js';
export { VUE_QUERY_CLIENT } from './utils.js';
export { VueQueryPlugin } from './vueQueryPlugin.js';
export type { VueQueryPluginOptions } from './vueQueryPlugin.js';
export * from '@tanstack/query-core';
